### ISSUE TITLE
RTD to start requiring build.os in .readthedocs.yml

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [dynamicslab/pysindy#396]
See the [blog post](https://blog.readthedocs.com/use-build-os-config/)

> Read the Docs will start requiring a build.os config key for all projects in order to build documentation successfully

Will need to add something like:
```
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
```
